### ISSUE TITLE
A few small README.md issues

### ISSUE THREAD

**Issue by kaneplusplus** [lucylgao/clusterpval-experiments#1]
The README.md file references several files that are not in the repository but are close in name.

1. `cond.R` is referenced - this should be `cond_power.R`, correct?
2. `our_type1_est.R` is reference but does not appear in the repository.

**Comment by lucylgao** [comment]
Thanks for pointing this out! 

1. Yes, it should be `cond_power.R`. README is now updated to reflect that. 
2. Apologies - somehow that file got left out when I updated for resubmission. This is fixed now.
